apiVersion: v1
kind: ConfigMap
metadata:
  name: common-feature-flags
  namespace: prod
data:
  FEATURE_FLAG_SQL: "true"
  FEATURE_FLAG_ADMIN_CLIENT: "true"
  FEATURE_FLAG_SIGNALHUB_WHITELIST: "false"
  FEATURE_FLAG_AGREEMENT_APPROVAL_POLICY_UPDATE: "true"
  FEATURE_FLAG_AGREEMENTS_CONTRACT_BUILDER: "true"
  FEATURE_FLAG_CLIENT_ASSERTION_STRICT_CLAIMS_VALIDATION: "false"
  FEATURE_FLAG_DELEGATIONS_CONTRACT_BUILDER: "true"
  FEATURE_FLAG_IMPROVED_PRODUCER_VERIFICATION_CLAIMS: "true"
  FEATURE_FLAG_NOTIFICATION_CONFIG: "false"
  FEATURE_FLAG_PURPOSE_TEMPLATE: "true"
  FEATURE_FLAG_PURPOSES_CONTRACT_BUILDER: "true"
  FEATURE_FLAG_ESERVICE_PERSONAL_DATA: "true"
