apiVersion: v1
kind: ConfigMap
metadata:
  name: common-in-app-notification-db
  namespace: prod
data:
  DB_HOST: "interop-platform-data-prod.cluster-cgo3fcsduspu.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "in_app_notification"
  DB_USE_SSL: "true"
  DB_SCHEMA: "prod_notification"
