apiVersion: v1
kind: ConfigMap
metadata:
  name: common-digest-tracking-db
  namespace: qa
data:
  DB_HOST_RW: "interop-platform-data-qa.cluster-cwgb5whmdqov.eu-south-1.rds.amazonaws.com"
  DB_HOST_RO: "interop-platform-data-qa.cluster-ro-cwgb5whmdqov.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "digest_tracking"
  DB_USE_SSL: "true"
  DB_SCHEMA: "qa_digest_tracking"