apiVersion: v1
kind: ConfigMap
metadata:
  name: common-safe-storage
  namespace: qa
data:
  BASE_URL: "http://vpce-0f17b997ad7e109cd-qh68uzeo.vpce-svc-075ebde4859d4c631.eu-south-1.vpce.amazonaws.com:8080"
  DOC_TYPE: "INTEROP_LEGAL_FACTS"
  DOC_STATUS: "SAVED"
  LIVE_REQUESTS_DYNAMO_TABLE_NAME: "interop-safe-storage-signature-tracking-qa"
