name: "interop-be-compute-agreements-consumer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-compute-agreements-consumer-dev-es1"

service:
  create: false

configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-compute-agreements-consumer"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-compute-agreements-consumer"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "latest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    AGREEMENT_PROCESS_URL: "common-services-urls.AGREEMENT_PROCESS_URL"
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    INTERNAL_JWT_KID: "common-jwt.INTERNAL_JWT_KID"
    INTERNAL_JWT_AUDIENCE: "common-jwt.INTERNAL_JWT_AUDIENCE"
    INTERNAL_JWT_SUBJECT: "common-jwt.INTERNAL_JWT_SUBJECT"
    INTERNAL_JWT_ISSUER: "common-jwt.INTERNAL_JWT_ISSUER"
    INTERNAL_JWT_SECONDS_DURATION: "common-jwt.INTERNAL_JWT_SECONDS_DURATION"
