apiVersion: v1
kind: ConfigMap
metadata:
  name: common-sqs
  namespace: dev-experimental-argocd-default-apps
data:
  APPLICATION_AUDIT_FALLBACK_SQS_URL: "#https://sqs.eu-south-1.amazonaws.com/505630707203/interop-analytics-application-audit-fallback-dev"
