name: interop-be-m2m-event-dispatcher
techStack: nodejs

serviceAccount:
  roleArn: "arn:aws:iam::533267098416:role/interop-be-m2m-event-dispatcher-att-es1"
  
service:
  create: false

configmap:
  KAFKA_GROUP_ID: "{{.Values.namespace}}-m2m-event-dispatcher"
  TOPIC_STARTING_OFFSET: "earliest"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "flyway-m2m-events"
    env:
      FLYWAY_CREATE_SCHEMAS: "true"
      FLYWAY_PLACEHOLDER_REPLACEMENT: "true"
      FLYWAY_PLACEHOLDERS_NAMESPACE: "{{.Values.namespace}}"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
    envFromConfigmaps:
      FLYWAY_SCHEMAS: "common-m2m-events-db.DB_SCHEMA"
      POSTGRES_DB: "common-m2m-events-db.DB_NAME"
      POSTGRES_HOST: "common-m2m-events-db.DB_HOST_RW"
      POSTGRES_PORT: "common-m2m-events-db.DB_PORT"
    envFromSecrets:
      FLYWAY_USER: "platform-data-flyway-user.username"
      FLYWAY_PASSWORD: "platform-data-flyway-user.password"

  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    AUTHORIZATION_TOPIC: "common-kafka.AUTHORIZATION_TOPIC"
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    ATTRIBUTE_TOPIC: "common-kafka.ATTRIBUTE_TOPIC"
    DELEGATION_TOPIC: "common-kafka.DELEGATION_TOPIC"
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    ESERVICE_TEMPLATE_TOPIC: "common-kafka.ESERVICE_TEMPLATE_TOPIC"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RW"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_PURPOSE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_PURPOSE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    M2M_EVENT_DB_NAME: "common-m2m-events-db.DB_NAME"
    M2M_EVENT_DB_HOST: "common-m2m-events-db.DB_HOST_RW"
    M2M_EVENT_DB_PORT: "common-m2m-events-db.DB_PORT"
    M2M_EVENT_DB_USE_SSL: "common-m2m-events-db.DB_USE_SSL"
    M2M_EVENT_DB_SCHEMA: "common-m2m-events-db.DB_SCHEMA"
  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-m2m-event-dispatcher-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-m2m-event-dispatcher-user.password"
    M2M_EVENT_DB_USERNAME: "platform-data-m2m-event-dispatcher-user.username"
    M2M_EVENT_DB_PASSWORD: "platform-data-m2m-event-dispatcher-user.password"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    KAFKA_CLIENT_ID: "metadata.name"
