name: busybox
techStack: "nodejs"

serviceAccount:
  roleArn: "fake"

service:
  create: true
  portName: http
  containerPort: 8080
  targetPort: 8080

deployment:
  image:
    repositoryPrefix: docker.io
    repositoryName: "busybox"
  command: [ "/bin/sh", "-c" ]
  args:
  - "mkdir -p /www; echo ok > /www/index.html; httpd -f -p 8080 -h /www"
