apiVersion: v1
kind: ConfigMap
metadata:
  name: common-read-model-sql
  namespace: att
data:
  DB_HOST_RW: "interop-platform-data-att.cluster-c5mm6mwy4v3q.eu-south-1.rds.amazonaws.com"
  DB_HOST_RO: "interop-platform-data-att.cluster-ro-c5mm6mwy4v3q.eu-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "read_model"
  DB_USE_SSL: "true"
  DB_SCHEMA_AGREEMENT: "att_agreement"
  DB_SCHEMA_ATTRIBUTE: "att_attribute"
  DB_SCHEMA_CATALOG: "att_catalog"
  DB_SCHEMA_CLIENT_JWK_KEY: "att_client_jwk_key"
  DB_SCHEMA_CLIENT: "att_client"
  DB_SCHEMA_DELEGATION: "att_delegation"
  DB_SCHEMA_ESERVICE_TEMPLATE: "att_eservice_template"
  DB_SCHEMA_NOTIFICATION_CONFIG: "att_notification_config"
  DB_SCHEMA_PRODUCER_JWK_KEY: "att_producer_jwk_key"
  DB_SCHEMA_PRODUCER_KEYCHAIN: "att_producer_keychain"
  DB_SCHEMA_PURPOSE: "att_purpose"
  DB_SCHEMA_PURPOSE_TEMPLATE: "att_purpose_template"
  DB_SCHEMA_TENANT: "att_tenant"
