apiVersion: v1
kind: ConfigMap
metadata:
  name: common-in-app-notification-db
  namespace: att
data:
  DB_HOST: "TBD"
  DB_PORT: "5432"
  DB_NAME: "in_app_notification"
  DB_USE_SSL: "true"
  DB_SCHEMA: "att_notification"
