apiVersion: v1
kind: ConfigMap
metadata:
  name: common-services-urls
  namespace: att
data:
  AGREEMENT_PROCESS_URL: "http://interop-be-agreement-process.att.svc.cluster.local:8088"
  ATTRIBUTE_REGISTRY_PROCESS_URL: "http://interop-be-attribute-registry-process.att.svc.cluster.local:8088"
  AUTHORIZATION_MANAGEMENT_URL: "http://interop-be-authorization-management.att.svc.cluster.local:8088/authorization-management/1.0"
  AUTHORIZATION_PROCESS_URL: "http://interop-be-authorization-process.att.svc.cluster.local:8088"
  CATALOG_PROCESS_URL: "http://interop-be-catalog-process.att.svc.cluster.local:8088"
  DELEGATION_PROCESS_URL: "http://interop-be-delegation-process.att.svc.cluster.local:8088"
  ESERVICE_TEMPLATE_PROCESS_URL: "http://interop-be-eservice-template-process.att.svc.cluster.local:8088"
  IN_APP_NOTIFICATION_MANAGER_URL: "http://interop-be-in-app-notification-manager.att.svc.cluster.local:8088"
  NOTIFICATION_CONFIG_PROCESS_URL: "http://interop-be-notification-config-process.att.svc.cluster.local:8088"
  NOTIFIER_URL: "http://interop-be-notifier.att.svc.cluster.local:8088/notifier/1.0"
  PURPOSE_PROCESS_URL: http://interop-be-purpose-process.att.svc.cluster.local:8088
  PURPOSE_TEMPLATE_PROCESS_URL: "http://interop-be-purpose-template-process.att.svc.cluster.local:8088"
  TENANT_PROCESS_URL: "http://interop-be-tenant-process.att.svc.cluster.local:8088"
