apiVersion: v1
kind: ConfigMap
metadata:
  name: common-s3
  namespace: dev
data:
  APPLICATION_DOCUMENTS_BUCKET: interop-application-documents-dev-es1
  GENERATED_JWT_DETAILS_BUCKET: interop-generated-jwt-details-dev-es1
  GENERATED_JWT_DETAILS_FALLBACK_BUCKET: interop-generated-jwt-details-fallback-dev-es1
  DATALAKE_DATA_EXPORT_BUCKET: interop-data-lake-exports-dev-es1
  DATALAKE_INTERFACE_EXPORT_BUCKET: interop-datalake-interface-export-dev-es1
  DOMAINS_EVENTS_BUCKET: "interop-domain-events-dev-es1"
  IVASS_BUCKET: interop-ivass-dev-es1
  APPLICATION_DATA_IMPORT_EXPORT_BUCKET: interop-application-import-export-dev-es1
  PRIVACY_NOTICES_CONTENT_BUCKET: interop-privacy-notices-content-dev-es1
  PRIVACY_NOTICES_HISTORY_BUCKET: interop-privacy-notices-history-dev-es1
  PUBLIC_CATALOG_BUCKET: interop-public-catalog-dev-es1
  ALLOW_LIST_BUCKET: interop-allow-list-dev-es1
  SIGNED_DOCUMENTS_BUCKET: "interop-signed-application-documents-dev-es1"
  SIGNED_EVENTS_BUCKET: "interop-signed-domain-events-dev-es1"
  SIGNED_AUDIT_BUCKET: "interop-signed-jwt-audit-dev-es1"

  AGREEMENT_CONSUMER_DOCUMENTS_PATH: "dev/generated-documents-unsigned/agreement"
  AGREEMENT_CONTRACTS_PATH: "dev/agreement/contracts"
  ALLOW_LIST_PATH: "allowlist"
  DATALAKE_INTERFACES_EXPORT_PATH: "data/interoperabilita/eservices/openapi/dev"  # DO NOT CHANGE, must match DL bucket path
  DELEGATION_DOCUMENTS_PATH: "dev/generated-documents-unsigned/delegation"
  DTD_CATALOG_STORAGE_PATH: "catalog"
  ESERVICE_DOCUMENTS_PATH: "eservices/docs"
  ESERVICE_TEMPLATE_DOCUMENTS_PATH: "eservice-template/docs"
  EXPORT_ESERVICE_PATH: "dev/eservices-export"
  IMPORT_ESERVICE_PATH: "dev/eservices-import"
  PRIVACY_NOTICES_PATH: "consent"
  PURPOSE_TEMPLATE_DOCUMENTS_PATH: "dev/purpose-template/docs"
  RISK_ANALYSIS_DOCUMENTS_PATH: "dev/generated-documents-unsigned/risk-analysis"
  TOKENS_JOB_BASE_DOCS_PATH: "token-details"
