name: "interop-be-selfcare-onboarding-consumer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-selfcare-onboarding-consumer-qa-es1"

service:
  create: false

configmap:
  KAFKA_BROKERS: "selc-u-eventhub-ns.servicebus.windows.net:9093"
  KAFKA_CLIENT_ID: "interop-qa"
  KAFKA_GROUP_ID: "interop-onboarding-qa"
  SELFCARE_TOPIC: "sc-contracts"
  RESET_CONSUMER_OFFSETS: "FALSE"
  INTEROP_PRODUCT: "prod-interop"
  ALLOWED_ORIGINS: "IPA,ANAC,IVASS,INFOCAMERE,SELC,SELC-PT,PDND_INFOCAMERE-SCP,PDND_INFOCAMERE-PRV,PDND_INFOCAMERE-PT,INFOCAMERE-PT"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "qa.interop-m2m"
  INTERNAL_JWT_ISSUER: "qa.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "qa.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"

deployment:
  replicas: 0
  envFromConfigmaps:
    TENANT_PROCESS_URL: "common-services-urls.TENANT_PROCESS_URL"
  envFromSecrets:
    KAFKA_BROKER_CONNECTION_STRING: "selfcare-v2.SELFCARE_BROKER_CONNECTION_STRING"
  resources:
    limits:
      cpu: "250m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "512Mi"
