name: interop-be-documents-generator
techStack: nodejs

serviceAccount:
  roleArn: "arn:aws:iam::{{.Values.local.awsAccountId}}:role/interop-be-documents-generator-{{.Values.local.env}}-es1"

service:
  create: false

configmap:
  KAFKA_GROUP_ID: "{{.Values.local.env}}-documents-generator"
  TOPIC_STARTING_OFFSET: "earliest"
  S3_BUCKET: "interop-application-documents-{{.Values.local.env}}-es1"
  DELEGATION_DOCUMENTS_PATH: "generated-documents/delegation"
  AGREEMENT_DOCUMENTS_PATH: "generated-documents/agreement"
  RISK_ANALYSIS_DOCUMENTS_PATH: "generated-documents/risk-analysis"
  RISK_ANALYSIS_TEMPLATE_DOCUMENTS_PATH: "generated-documents/risk-analysis-template"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-documents-generator"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"

deployment:
  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    DELEGATION_TOPIC: "common-kafka.DELEGATION_TOPIC"
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    PURPOSE_TEMPLATE_TOPIC: "common-kafka.PURPOSE_TEMPLATE_TOPIC"
    AUTHORIZATION_TOPIC: "common-kafka.AUTHORIZATION_TOPIC"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_PURPOSE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_PURPOSE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    AGREEMENT_PROCESS_URL: "common-services-urls.AGREEMENT_PROCESS_URL"
    DELEGATION_PROCESS_URL: "common-services-urls.DELEGATION_PROCESS_URL"
    PURPOSE_PROCESS_URL: "common-services-urls.PURPOSE_PROCESS_URL"
    PURPOSE_TEMPLATE_PROCESS_URL: "common-services-urls.PURPOSE_TEMPLATE_PROCESS_URL"
  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-documents-generator-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-documents-generator-user.password"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    KAFKA_CLIENT_ID: "metadata.name"
