name: "interop-be-selfcare-onboarding-consumer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::565393043798:role/interop-be-selfcare-onboarding-consumer-vapt-es1"

service:
  create: false

configmap:
  KAFKA_BROKERS: "selc-u-eventhub-ns.servicebus.windows.net:9093"
  KAFKA_CLIENT_ID: "interop-{{.Values.namespace}}"
  KAFKA_GROUP_ID: "interop-onboarding-{{.Values.namespace}}"
  SELFCARE_TOPIC: "sc-contracts"
  RESET_CONSUMER_OFFSETS: "FALSE"
  INTEROP_PRODUCT: "prod-interop-atst"
  ALLOWED_ORIGINS: "IPA,ANAC,IVASS,INFOCAMERE,SELC,SELC-PT,PDND_INFOCAMERE-SCP,PDND_INFOCAMERE-PRV,PDND_INFOCAMERE-PT,INFOCAMERE-PT"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-m2m"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"

deployment:
  replicas: 0
  envFromConfigmaps:
    TENANT_PROCESS_URL: "common-services-urls.TENANT_PROCESS_URL"
  envFromSecrets:
    KAFKA_BROKER_CONNECTION_STRING: "selfcare-v2.SELFCARE_BROKER_CONNECTION_STRING"
