name: "interop-be-party-registry-proxy-refresher"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-party-registry-proxy-refresher-qa-es1"

cronjob:
  schedule: "0 6 * * *"
  suspend: true
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  command: ["bin/sh"]
  args: ["-c", "echo \"Job Started\" && ./entrypoint.sh -X POST -sS $(PARTY_REGISTRY_PROXY_URL)/reload && echo \"Job Completed\""]
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    PARTY_REGISTRY_PROXY_URL: "common-services-urls.PARTY_REGISTRY_PROXY_URL"