name: interop-be-notification-tenant-lifecycle-consumer
techStack: nodejs

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-notification-tenant-lifecycle-consumer-dev-es1"

service:
  create: false

configmap:
  KAFKA_GROUP_ID: "{{.Values.namespace}}-notification-tenant-lifecycle-consumer"
  TOPIC_STARTING_OFFSET: "earliest"

deployment:
  envFromConfigmaps:
    INTERNAL_JWT_AUDIENCE: "common-jwt.INTERNAL_JWT_AUDIENCE"
    INTERNAL_JWT_ISSUER: "common-jwt.INTERNAL_JWT_ISSUER"
    INTERNAL_JWT_KID: "common-jwt.INTERNAL_JWT_KID"
    INTERNAL_JWT_SUBJECT: "common-jwt.INTERNAL_JWT_SUBJECT"
    INTERNAL_JWT_SECONDS_DURATION: "common-jwt.INTERNAL_JWT_SECONDS_DURATION"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    NOTIFICATION_CONFIG_PROCESS_URL: "common-services-urls.NOTIFICATION_CONFIG_PROCESS_URL"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    KAFKA_CLIENT_ID: "metadata.name"
