apiVersion: v1
kind: ServiceAccount
metadata:
  name: refresh-sa
  namespace: dev-experimental-argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: refresh-role
  namespace: dev-experimental-argocd
rules:
  - apiGroups: ["argoproj.io"]
    resources:
      - applications
      - applicationsets
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: refresh-rolebinding
  namespace: dev-experimental-argocd
subjects:
  - kind: ServiceAccount
    name: refresh-sa
    namespace: dev-experimental-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: refresh-role
---
apiVersion: batch/v1
kind: Job
metadata:
  name: force-refresh
  namespace: dev-experimental-argocd-interop-apps
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: refresh-sa
      restartPolicy: Never
      containers:
        - name: refresher
          image: bitnami/kubectl:latest
          command:
            - sh
            - -c
            - |
              echo "Forcing hard refresh on target applications..."
              
              kubectl patch applicationset interop-microservices-appset-post-sync-hook \
                -n dev-experimental-argocd \
                --type merge \
                -p '{"metadata":{"annotations":{"argocd.argoproj.io/refresh":"hard"}}}'
