apiVersion: v1
kind: ConfigMap
metadata:
  name: common-useless-postsync-hook
  namespace: dev-experimental-argocd-interop-apps
data:
  NOT_REFERENCED_1: "this is a useless configmap that should not trigger the post-sync hook"