apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - emailsender.manualrefresh.externalsecret.yaml
  - eso.secretstore.yaml
  - eso.serviceaccount.yaml
  - experimentaleso.externalsecret.yaml
  - externalsecret.markertest.yaml
  - secret.markertest.yaml

patches:
  - target:
      kind: ExternalSecret
      name: experimental-eso-markertest
    patch: |-
      - op: replace
        path: /spec/target/template/metadata/annotations/externalsecret~1secret-applied-hash
        value: "v5"
  - target:
      kind: Secret
      name: experimental-eso-markertest
    patch: |-
      - op: replace
        path: /metadata/annotations/externalsecret~1secret-contract-hash
        value: "v5"
