name: "interop-be-m2m-gateway-v3"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-m2m-gateway-v3-dev-es1"

service:
  create: true
  containerPort: 8088
  albHealthCheck:
    path: /m2m-gateway/v3/status
    port: "8088"
    protocol: HTTP

configmap:
  M2M_GATEWAY_INTERFACE_VERSION: v3
  ACCEPTED_AUDIENCES: "{{.Values.namespace}}.interop.pagopa.it/m2m"
  RATE_LIMITER_MAX_REQUESTS: "9999999"
  RATE_LIMITER_BURST_PERCENTAGE: "1.0"
  RATE_LIMITER_RATE_INTERVAL_MILLIS: "1000"
  RATE_LIMITER_TIMEOUT_MILLIS: "300"
  DEFAULT_POLLING_RETRY_DELAY: "300"
  DEFAULT_POLLING_MAX_RETRIES: "20"
  ESERVICE_DOCUMENTS_CONTAINER: "interop-application-documents-{{.Values.namespace}}-es1"
  ESERVICE_DOCUMENTS_PATH: "eservices/docs"
  ESERVICE_TEMPLATE_DOCUMENTS_CONTAINER: "interop-application-documents-{{.Values.namespace}}-es1"
  ESERVICE_TEMPLATE_DOCUMENTS_PATH: "eservice-template/docs"
  RISK_ANALYSIS_DOCUMENTS_CONTAINER: "interop-application-documents-{{.Values.namespace}}-es1"
  RISK_ANALYSIS_DOCUMENTS_PATH: "{{.Values.namespace}}/risk-analysis/docs"
  AGREEMENT_CONSUMER_DOCUMENTS_CONTAINER: "interop-application-documents-{{.Values.namespace}}-es1"
  AGREEMENT_CONSUMER_DOCUMENTS_PATH: "{{.Values.namespace}}/agreement/consumer-docs"
  AGREEMENT_CONSUMER_CONTRACTS_PATH: "{{.Values.namespace}}/agreement/contracts"
  PURPOSE_TEMPLATE_DOCUMENTS_CONTAINER: "interop-application-documents-{{.Values.namespace}}-es1"
  PURPOSE_TEMPLATE_DOCUMENTS_PATH: "{{.Values.namespace}}/purpose-template/docs"
  DPOP_CACHE_TABLE: "interop-m2m-gateway-dpop-cache-dev"
  DPOP_HTU_BASE: "https://api.dev.interop.pagopa.it/v3"
  DPOP_IAT_TOLERANCE_SECONDS: "10"
  DPOP_DURATION_SECONDS: "60"
  INTEGRITY_REST_JWT_KID: 4d77e2ff-2b3a-42bf-b215-1f140ad036a0
  INTEGRITY_REST_JWT_ISSUER: "api.dev.interop.pagopa.it/v3"
  INTEGRITY_REST_JWT_SECONDS_DURATION: 100

deployment:
  env:
    HOST: "0.0.0.0"
    PORT: "8088"
    SERVICE_VERSION: "{{.Values.deployment.image.tag}}"
    KEEP_ALIVE_TIMEOUT_MILLIS: "61000"
  envFromFieldRef:
    POD_NAME: "metadata.name"
    NODE_IP: "status.hostIP"
    AWS_ROLE_SESSION_NAME: "metadata.name"
    PRODUCER_KAFKA_CLIENT_ID: "metadata.name"
  envFromConfigmaps:
    WELL_KNOWN_URLS: "common-jwt.WELL_KNOWN_URLS"
    AGREEMENT_PROCESS_URL: "common-services-urls.AGREEMENT_PROCESS_URL"
    ATTRIBUTE_REGISTRY_PROCESS_URL: "common-services-urls.ATTRIBUTE_REGISTRY_PROCESS_URL"
    AUTHORIZATION_PROCESS_URL: "common-services-urls.AUTHORIZATION_PROCESS_URL"
    CATALOG_PROCESS_URL: "common-services-urls.CATALOG_PROCESS_URL"
    DELEGATION_PROCESS_URL: "common-services-urls.DELEGATION_PROCESS_URL"
    ESERVICE_TEMPLATE_PROCESS_URL: "common-services-urls.ESERVICE_TEMPLATE_PROCESS_URL"
    PURPOSE_PROCESS_URL: "common-services-urls.PURPOSE_PROCESS_URL"
    PURPOSE_TEMPLATE_PROCESS_URL: "common-services-urls.PURPOSE_TEMPLATE_PROCESS_URL"
    TENANT_PROCESS_URL: "common-services-urls.TENANT_PROCESS_URL"
    EVENT_MANAGER_URL: "common-services-urls.EVENT_MANAGER_URL"
    APPLICATION_AUDIT_TOPIC: "common-kafka.APPLICATION_AUDIT_TOPIC"
    APPLICATION_AUDIT_FALLBACK_SQS_URL: "common-sqs.APPLICATION_AUDIT_FALLBACK_SQS_URL"
    PRODUCER_KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    RATE_LIMITER_REDIS_HOST: "common-redis.REDIS_HOST"
    RATE_LIMITER_REDIS_PORT: "common-redis.REDIS_PORT"
    SELFCARE_V2_URL: "common-selfcare.SELFCARE_V2_URL"
  envFromSecrets:
    SELFCARE_V2_API_KEY: "selfcare-v2.SELFCARE_V2_API_KEY"
  livenessProbe:
    httpGet:
      path: "/m2m-gateway/v3/status"
      port: http
    initialDelaySeconds: 15
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: "/m2m-gateway/v3/status"
      port: http
    initialDelaySeconds: 15
    periodSeconds: 5
