name: "interop-be-agreement-outbound-writer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-agreement-outbound-writer-dev-es1"

service:
  create: false

deployment:
  args: ["echo 'hello there'; sleep 3000; exit 0;"]
  envFromConfigmaps:
    PRODUCER_KAFKA_CLIENT_ID: "{{.Values.name}}.KAFKA_CLIENT_ID"
    AGREEMENT_TOPIC: "common-kafka-postsync-hook.AGREEMENT_TOPIC"
    AGREEMENT_OUTBOUND_TOPIC: "common-kafka-postsync-hook.AGREEMENT_OUTBOUND_TOPIC"
    