name: "post-sync-app1"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/post-sync-app1-dev-es1"

service:
  create: false

deployment:
  args: ["echo 'hello there'; sleep 3000; exit 0;"]
  env:
    dbhash: "{{ .Values.locals.secrets.dbhash }}"
  envFromConfigmaps:
    AGREEMENT_TOPIC: "common-kafka-postsync-hook.AGREEMENT_TOPIC"
    AGREEMENT_OUTBOUND_TOPIC: "common-kafka-postsync-hook.AGREEMENT_OUTBOUND_TOPIC"
    
locals:
  externalSecrets:
    remoteSecrets:
    - id: "experimental-eso/foo/bar"
      version: "862ccc7f-36bf-4fe5-bc41-1f7c3a8c0a89"
    - id: "rds/interop-platform-data-dev/users/dev_email_digest_dispatcher_user"
      version: "terraform-20260212133048976200000002"