name: "interop-be-datalake-interface-exporter"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-datalake-interface-exporter-dev-es1"

service:
  create: false

configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-datalake-interface-exporter"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-datalake-interface-exporter"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "earliest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    ESERVICE_DOCUMENTS_S3_BUCKET: "common-s3.APPLICATION_DOCUMENTS_BUCKET"
    DATALAKE_INTERFACES_EXPORT_S3_BUCKET: "common-s3.APPLICATION_DATA_IMPORT_EXPORT_BUCKET"
    DATALAKE_INTERFACES_EXPORT_PATH: "common-s3.DATALAKE_INTERFACES_EXPORT_PATH"
  resources:
    limits:
      cpu: "500m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "2Gi"
