name: interop-be-in-app-notification-dispatcher
techStack: nodejs

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-in-app-notification-dispatcher-qa-es1"

service:
  create: false

configmap:
  KAFKA_GROUP_ID: "{{.Values.namespace}}-in-app-notification-dispatcher"
  TOPIC_STARTING_OFFSET: "latest"

deployment:
  flywayInitContainer:
    create: true
    migrationsConfigmap: "flyway-in-app-notification"
    env:
      FLYWAY_CREATE_SCHEMAS: true
      FLYWAY_PLACEHOLDER_REPLACEMENT: true
      FLYWAY_PLACEHOLDERS_NAMESPACE: "{{.Values.namespace}}"
      FLYWAY_URL: jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)
      FLYWAY_SCHEMAS: "{{.Values.namespace}}_notification"
    envFromConfigmaps:
      POSTGRES_HOST: "common-in-app-notification-db.DB_HOST"
      POSTGRES_PORT: "common-in-app-notification-db.DB_PORT"
      POSTGRES_DB: "common-in-app-notification-db.DB_NAME"
    envFromSecrets:
      FLYWAY_USER: "platform-data-flyway-user.username"
      FLYWAY_PASSWORD: "platform-data-flyway-user.password"

  envFromConfigmaps:
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    ATTRIBUTE_TOPIC: "common-kafka.ATTRIBUTE_TOPIC"
    AUTHORIZATION_TOPIC: "common-kafka.AUTHORIZATION_TOPIC"
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    DELEGATION_TOPIC: "common-kafka.DELEGATION_TOPIC"
    ESERVICE_TEMPLATE_TOPIC: "common-kafka.ESERVICE_TEMPLATE_TOPIC"
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    IN_APP_NOTIFICATION_DB_HOST: "common-in-app-notification-db.DB_HOST"
    IN_APP_NOTIFICATION_DB_PORT: "common-in-app-notification-db.DB_PORT"
    IN_APP_NOTIFICATION_DB_NAME: "common-in-app-notification-db.DB_NAME"
    IN_APP_NOTIFICATION_DB_USE_SSL: "common-in-app-notification-db.DB_USE_SSL"
    IN_APP_NOTIFICATION_DB_SCHEMA: "common-in-app-notification-db.DB_SCHEMA"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_PURPOSE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_PURPOSE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
  envFromSecrets:
    IN_APP_NOTIFICATION_DB_USERNAME: "platform-data-in-app-notification-dispatcher-user.username"
    IN_APP_NOTIFICATION_DB_PASSWORD: "platform-data-in-app-notification-dispatcher-user.password"
    READMODEL_SQL_DB_USERNAME: "platform-data-in-app-notification-dispatcher-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-in-app-notification-dispatcher-user.password"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    KAFKA_CLIENT_ID: "metadata.name"
