name: interop-be-notification-user-lifecycle-consumer
techStack: nodejs

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-notification-user-lifecycle-consumer-dev-es1"

service:
  create: false

configmap:
  KAFKA_GROUP_ID: "{{.Values.namespace}}-notification-user-lifecycle-consumer"
  TOPIC_STARTING_OFFSET: "latest"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-m2m"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "1800"
  INTEROP_PRODUCT: "prod-interop"

deployment:
  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    NOTIFICATION_CONFIG_PROCESS_URL: "common-services-urls.NOTIFICATION_CONFIG_PROCESS_URL"
    READMODEL_SQL_DB_HOST: "common-read-model-sql.DB_HOST_RO"
    READMODEL_SQL_DB_PORT: "common-read-model-sql.DB_PORT"
    READMODEL_SQL_DB_NAME: "common-read-model-sql.DB_NAME"
    READMODEL_SQL_DB_USE_SSL: "common-read-model-sql.DB_USE_SSL"
    READMODEL_SQL_DB_SCHEMA_AGREEMENT: "common-read-model-sql.DB_SCHEMA_AGREEMENT"
    READMODEL_SQL_DB_SCHEMA_ATTRIBUTE: "common-read-model-sql.DB_SCHEMA_ATTRIBUTE"
    READMODEL_SQL_DB_SCHEMA_CATALOG: "common-read-model-sql.DB_SCHEMA_CATALOG"
    READMODEL_SQL_DB_SCHEMA_CLIENT_JWK_KEY: "common-read-model-sql.DB_SCHEMA_CLIENT_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_CLIENT: "common-read-model-sql.DB_SCHEMA_CLIENT"
    READMODEL_SQL_DB_SCHEMA_DELEGATION: "common-read-model-sql.DB_SCHEMA_DELEGATION"
    READMODEL_SQL_DB_SCHEMA_ESERVICE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_ESERVICE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_NOTIFICATION_CONFIG: "common-read-model-sql.DB_SCHEMA_NOTIFICATION_CONFIG"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_JWK_KEY: "common-read-model-sql.DB_SCHEMA_PRODUCER_JWK_KEY"
    READMODEL_SQL_DB_SCHEMA_PRODUCER_KEYCHAIN: "common-read-model-sql.DB_SCHEMA_PRODUCER_KEYCHAIN"
    READMODEL_SQL_DB_SCHEMA_PURPOSE: "common-read-model-sql.DB_SCHEMA_PURPOSE"
    READMODEL_SQL_DB_SCHEMA_PURPOSE_TEMPLATE: "common-read-model-sql.DB_SCHEMA_PURPOSE_TEMPLATE"
    READMODEL_SQL_DB_SCHEMA_TENANT: "common-read-model-sql.DB_SCHEMA_TENANT"
    SELFCARE_TOPIC: "common-selfcare.SELFCARE_USERS_TOPIC"
  envFromSecrets:
    READMODEL_SQL_DB_USERNAME: "platform-data-notification-user-lifecycle-consumer-user.username"
    READMODEL_SQL_DB_PASSWORD: "platform-data-notification-user-lifecycle-consumer-user.password"
    KAFKA_BROKER_CONNECTION_STRING: "selfcare-v2.SELFCARE_USERS_BROKER_CONNECTION_STRING"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
    KAFKA_CLIENT_ID: "metadata.name"
