namespace: dev-experimental-argocd-interop-apps

service:
  targetPort: http
  portName: http

deployment:
  enableRolloutAnnotations: true
  replicas: 1
  command: [ "/bin/sh", "-c" ]
  args: [ "echo 'hello there'; sleep 3000; exit 0;" ]
  image:
    repositoryPrefix: "docker.io"
    #repositoryPrefix: "505630707203.dkr.ecr.eu-south-1.amazonaws.com"
    imagePullPolicy: Always
    tag: "20"
    repositoryName: "node"
    #tag: $IMAGE_TAG_PLACEHOLDER
    #digest: $IMAGE_DIGEST_PLACEHOLDER
  env:
    LOG_LEVEL: "info"
    NODE_ENV: "production"
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  flywayInitContainer:
    create: false

local:
  interop_be_commons:
    RSA_KEYS_IDENTIFIERS: "aca0625c-e107-42ae-944a-158422af5d92"
    DEV_ENDPOINTS_ENABLED: "true"
    ENABLED_PROJECTIONS: "false"
  awsAccountId: "505630707203"
  env: "dev"
  externalSecrets:
    markerValue: "v1"
    remoteSecrets:
    - id: "experimental-eso/foo/bar"
      version: "862ccc7f-36bf-4fe5-bc41-1f7c3a8c0a89"
    - id: "rds/interop-platform-data-dev/users/dev_email_digest_dispatcher_user"
      version: "terraform-20260212133048976200000002"

autoscaling:
  keda:
    create: false

locals:
  secrets:
    dbhash: "fakehash_new"